CREATE NONCLUSTERED INDEX [IX_OPETICK03] ON [dbo].[ope.ope_tick_04_det_entregadistri] ([rela_opetick03] ASC) INCLUDE ([id_opetick04])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE INDEX [UX_DISTRITO_BASE_COCHE] ON [par.par_enti_03_cab_coches] (RELA_PARENTI01, RELA_PARENTI02, ID_PARENTI03)
CREATE INDEX [IX_ID_EMPRESA_LINEA] ON [par.par_enti_03_cab_coches] (ID_PARENTI03, RELA_PARENTI01, RELA_PARENTI02)

DROP INDEX [ID_EMPRESA] ON [par.par_enti_03_cab_coches]
DROP INDEX [IX_Emp_Coche_Fecha] ON [dbo].[ope.ope_posi_07_cab_datamart]

CREATE NONCLUSTERED INDEX [IX_ID_EMPRESA_LINEA] ON [dbo].[par.par_enti_03_cab_coches]
(
	[id_parenti03] ASC,
	[rela_parenti01] ASC,
	[rela_parenti02] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE STATISTICS [STAT_PARENTI03_PARENTI02] ON [dbo].[par.par_enti_03_cab_coches]([id_parenti03], [rela_parenti02])