BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[ope.ope_tick_04_det_entregadistri] ADD
	opetick04_comentario1 varchar(50) NULL,
	opetick04_comentario2 varchar(50) NULL,
	opetick04_comentario3 varchar(50) NULL
GO
ALTER TABLE dbo.[ope.ope_tick_04_det_entregadistri] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
