USE [logictracker]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.[par.par_enti_58_insumos] ADD
	parenti58_valor_referencia float(53) NULL
GO
ALTER TABLE dbo.[par.par_enti_58_insumos] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
