BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[par.par_enti_16_tbl_tipomensaje] ADD
	parenti16_de_confirmacion bit NULL,
	parenti16_de_rechazo bit NULL
GO
ALTER TABLE dbo.[par.par_enti_16_tbl_tipomensaje] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
