USE [logictracker]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[par.par_even_02_tbl_acciones] ADD
	pareven02_envia_reporte bit NULL,
	pareven02_reporte varchar(128) NULL,
	pareven02_mail_reporte varchar(MAX) NULL
GO
ALTER TABLE dbo.[par.par_even_02_tbl_acciones] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
