USE [logictracker]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[ope.ope_tick_06_tick_datamart] ADD
	opetick06_confirmacion varchar(64) NULL
GO
ALTER TABLE dbo.[ope.ope_tick_06_tick_datamart] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
