USE [logictracker]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.[par.par_enti_08_cab_dispositivos] ADD
	parenti08_device_id int NULL
GO
ALTER TABLE dbo.[par.par_enti_08_cab_dispositivos] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
GO
UPDATE [par.par_enti_08_cab_dispositivos]
SET parenti08_device_id = id_parenti08
GO
COMMIT