//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logictracker.Reportes.Estadistica {
    
    
    public partial class ReportesEstadisticaIdleTimes {
        
        /// <summary>
        /// lblDistrito control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblDistrito;
        
        /// <summary>
        /// ddlDistrito control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.DropDownLists.LocacionDropDownList ddlDistrito;
        
        /// <summary>
        /// lblFechaDesde control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblFechaDesde;
        
        /// <summary>
        /// dtpDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Input.DateTimePicker dtpDate;
        
        /// <summary>
        /// chkUndefined control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.CheckBoxs.ResourceCheckBox chkUndefined;
        
        /// <summary>
        /// lblBase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Buttons.ResourceLinkButton lblBase;
        
        /// <summary>
        /// upBase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upBase;
        
        /// <summary>
        /// lbBase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.ListBoxs.PlantaListBox lbBase;
    }
}
