//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logictracker.Reportes.Estadistica {
    
    
    public partial class EstadisticaMobilesKilometers {
        
        /// <summary>
        /// lblLocacion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblLocacion;
        
        /// <summary>
        /// ddlLocacion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.DropDownLists.LocacionDropDownList ddlLocacion;
        
        /// <summary>
        /// lblPlanta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblPlanta;
        
        /// <summary>
        /// upPlanta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upPlanta;
        
        /// <summary>
        /// ddlPlanta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.DropDownLists.PlantaDropDownList ddlPlanta;
        
        /// <summary>
        /// lblTipoVehiculo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblTipoVehiculo;
        
        /// <summary>
        /// upTipo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upTipo;
        
        /// <summary>
        /// ddlTipoVehiculo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.DropDownLists.TipoDeVehiculoDropDownList ddlTipoVehiculo;
        
        /// <summary>
        /// lblTransportista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblTransportista;
        
        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// ddlTransportista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.DropDownLists.TransportistaDropDownList ddlTransportista;
        
        /// <summary>
        /// lnkMoviles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Buttons.ResourceLinkButton lnkMoviles;
        
        /// <summary>
        /// upMovil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upMovil;
        
        /// <summary>
        /// lbMobiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.ListBoxs.MovilListBox lbMobiles;
        
        /// <summary>
        /// lblDesde control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblDesde;
        
        /// <summary>
        /// dpDesde control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Input.DateTimePicker dpDesde;
        
        /// <summary>
        /// lblHasta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblHasta;
        
        /// <summary>
        /// dpHasta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Input.DateTimePicker dpHasta;
        
        /// <summary>
        /// baloontip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.Popup.BaloonTip baloontip;
        
        /// <summary>
        /// dpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Input.DateTimeRangeValidator dpValidator;
        
        /// <summary>
        /// chkEnCiclo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.CheckBoxs.ResourceCheckBox chkEnCiclo;
    }
}
