Garmin Fleet Management Controller: ApplicationLayer Class Reference
ApplicationLayer Class Reference
Abstract base class for the application layer in the OSI //! model //!
#include <ApplicationLayer.h>