Garmin Fleet Management Controller: CStopListDlg Class Reference
CStopListDlg Class Reference
Modeless dialog allowing the user to manage the A603 stops //! on the client device. //!
#include <CStopListDlg.h>