Garmin Fleet Management Controller: FileBackedMap< T > Class Template Reference
FileBackedMap< T > Class Template Reference
Map whose contents are also saved to a file. //!
#include <FileBackedMap.h>
Public Types
typedef std::map< key_type, T >
::const_iterator const_iterator
Iterator for read-only traversal through the map.
typedef T::key_type key_type
key type
Public Member Functions
FileBackedMap (const char *aFileName)
Create a new FileBackedMap //!
const_iterator begin ()
Iterator positioned at the first element in the map.
void clear ()
Remove all elements from the map.
bool contains (const key_type &aKey)
Check whether the specified key is in the map
uint32 count () const
The number of items in the map //!
bool empty ()
Check whether the map is empty //!
const_iterator end ()
Iterator positioned after the last element in the map.
T & get (const key_type &aKey)
Get the item by key //!
const key_type & getKeyAt (uint32 aIndex) const
Get the key for the item at a given list index /.
void put (T &aValue)
Add (or replace) an item in the map //!
void remove (const key_type &aKey)
Remove an item from the map //!
void save ()
Save the map to disk.
uint32 validCount () const
The number of valid items in the map //!
Private Member Functions
void load ()
Read the contents of the backing file into the map //!
Private Attributes
const char * mFileName
The name of the file that this map is saved to.
std::vector< key_type > mKeyList
Map of indexes to keys.
std::map< key_type, T > mMap
The underlying map in memory.
Detailed Description
template<class T>
class FileBackedMap< T >
Map whose contents are also saved to a file. //!
A FileBackedMap is a map of uint32 to a value type. Each value in the map for which isValid() returns TRUE is saved to //! a text file, with one line per item. //! //! Methods are provided to add/replace, remove, check for, and get //! items from the underlying map, iterate through the items in the map, and clear the map's contents. All keep the underlying file //! in sync. //! //!
Template Parameters:
T The value type for items in the map. //!
Since:
Protocol A603
Definition at line 32 of file FileBackedMap.h.
Member Typedef Documentation
template<class T> typedef std::map<key_type, T>::const_iterator FileBackedMap< T >::const_iterator
Iterator for read-only traversal through the map.
Definition at line 54 of file FileBackedMap.h.
template<class T> typedef T::key_type FileBackedMap< T >::key_type
key type
Definition at line 36 of file FileBackedMap.h.
Constructor & Destructor Documentation
template<class T> FileBackedMap< T >::FileBackedMap (const char * aFileName) [inline]
Create a new FileBackedMap //!
Construct a FileBackedMap and load all items from file //!
Parameters:
aFileName The file associated with this map. //!
Note:
In this implementation, aFileName must be static const; the //! name is referenced, not copied.
Definition at line 46 of file FileBackedMap.h.
Member Function Documentation
template<class T> const_iterator FileBackedMap< T >::begin () [inline]
Iterator positioned at the first element in the map.
Definition at line 59 of file FileBackedMap.h.
Referenced by FmiApplicationLayer::getNextStopId(), CFmiPcAppDlg::initStopList(), CFmiPcAppDlg::OnBnClickedEnable(), CSelectCannedResponseDlg::OnInitDialog(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendDeleteWaypointCat(), CWaypointDlg::updateCatBox(), CWaypointDlg::updateListBox(), CManageCannedResponseDlg::updateListBox(), CDriverLoginDlg::updateListBox(), CDriverIdAndStatusDlg::updateListBox(), and CCannedTxtMsgDlg::updateListBox().
template<class T> void FileBackedMap< T >::clear () [inline]
Remove all elements from the map.
Definition at line 88 of file FileBackedMap.h.
Referenced by FmiApplicationLayer::resetCannedMessages(), FmiApplicationLayer::resetCannedResponseMessages(), FmiApplicationLayer::resetCannedResponses(), FmiApplicationLayer::resetDriverStatusList(), FmiApplicationLayer::resetSavedStops(), and FmiApplicationLayer::resetWaypoints().
template<class T> bool FileBackedMap< T >::contains (const key_type & aKey) [inline]
Check whether the specified key is in the map
Parameters:
aKey The key to look for //!
Returns:
true if the item is in the map, false otherwise
Definition at line 78 of file FileBackedMap.h.
Referenced by FmiApplicationLayer::getNextStopId(), CStopListDlg::OnEventStopListChanged(), and CStopNewDlg::OnFormChanged().
template<class T> uint32 FileBackedMap< T >::count () const [inline]
The number of items in the map //!
Returns:
The total number of items in the map
Definition at line 197 of file FileBackedMap.h.
template<class T> bool FileBackedMap< T >::empty () [inline]
Check whether the map is empty //!
Returns:
true if there are no elements in the map, false otherwise
Definition at line 163 of file FileBackedMap.h.
Referenced by FmiApplicationLayer::getNextStopId().
template<class T> const_iterator FileBackedMap< T >::end () [inline]
Iterator positioned after the last element in the map.
Definition at line 67 of file FileBackedMap.h.
Referenced by FmiApplicationLayer::getNextStopId(), CFmiPcAppDlg::initStopList(), CFmiPcAppDlg::OnBnClickedEnable(), CSelectCannedResponseDlg::OnInitDialog(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendDeleteWaypointCat(), CWaypointDlg::updateCatBox(), CWaypointDlg::updateListBox(), CManageCannedResponseDlg::updateListBox(), CDriverLoginDlg::updateListBox(), CDriverIdAndStatusDlg::updateListBox(), and CCannedTxtMsgDlg::updateListBox().
template<class T> T& FileBackedMap< T >::get (const key_type & aKey) [inline]
Get the item by key //!
Get the item with the specified key, creating it if it //! is not already in the map. //!
Parameters:
aKey The key of the item to retrieve //!
Returns:
The item with the specified key.
Definition at line 102 of file FileBackedMap.h.
Referenced by CDriverLoginDlg::OnBnClickedSet(), CStopListDlg::OnEventStopListChanged(), CDriverLoginDlg::OnLbnSelchangeDriverList(), and CDriverIdAndStatusDlg::OnLbnSelchangeStatuslist().
template<class T> const key_type& FileBackedMap< T >::getKeyAt (uint32 aIndex) const [inline]
Get the key for the item at a given list index /.
Parameters:
aIndex The key of the item to retrieve. Must be less than //! validCount(). //!
Returns:
The key of the item at the specified index.
Definition at line 119 of file FileBackedMap.h.
Referenced by CWaypointDlg::getCatIds(), CManageCannedResponseDlg::OnBnClickedDelete(), CDriverLoginDlg::OnBnClickedDelete(), CDriverIdAndStatusDlg::OnBnClickedDelete(), CCannedTxtMsgDlg::OnBnClickedDelete(), CSelectCannedResponseDlg::OnBnClickedOk(), CDriverIdAndStatusDlg::OnBnClickedSendDriverStatus(), CWaypointDlg::OnBnClickedWptBtnDelete(), CDriverLoginDlg::OnLbnSelchangeDriverList(), and CDriverIdAndStatusDlg::OnLbnSelchangeStatuslist().
template<class T> void FileBackedMap< T >::load () [inline, private]
Read the contents of the backing file into the map //!
Load all items from mFileName into mMap.
Definition at line 216 of file FileBackedMap.h.
Referenced by FileBackedMap< StopListItem >::FileBackedMap().
template<class T> void FileBackedMap< T >::put (T & aValue) [inline]
Add (or replace) an item in the map //!
Parameters:
aValue The item to add
Definition at line 133 of file FileBackedMap.h.
Referenced by CDriverLoginDlg::OnBnClickedSet().
template<class T> void FileBackedMap< T >::remove (const key_type & aKey) [inline]
Remove an item from the map //!
Parameters:
aKey The key of the item to remove
Definition at line 147 of file FileBackedMap.h.
Referenced by CDriverLoginDlg::OnBnClickedDelete().
template<class T> void FileBackedMap< T >::save () [inline]
Save the map to disk.
Definition at line 171 of file FileBackedMap.h.
Referenced by FileBackedMap< StopListItem >::clear(), FileBackedMap< StopListItem >::put(), FileBackedMap< StopListItem >::remove(), WaypointListItem::save(), DriverLoginItem::save(), and ClientListItem::save().
template<class T> uint32 FileBackedMap< T >::validCount () const [inline]
The number of valid items in the map //!
Returns:
The number of valid items in the map
Definition at line 206 of file FileBackedMap.h.
Referenced by CDriverIdAndStatusDlg::OnBnClickedDelete().
Member Data Documentation
template<class T> const char* FileBackedMap< T >::mFileName [private]
The name of the file that this map is saved to.
Definition at line 240 of file FileBackedMap.h.
Referenced by FileBackedMap< StopListItem >::load(), and FileBackedMap< StopListItem >::save().
template<class T> std::vector<key_type> FileBackedMap< T >::mKeyList [private]
Map of indexes to keys.
Definition at line 246 of file FileBackedMap.h.
Referenced by FileBackedMap< StopListItem >::getKeyAt(), FileBackedMap< StopListItem >::load(), FileBackedMap< StopListItem >::save(), and FileBackedMap< StopListItem >::validCount().
template<class T> std::map<key_type, T> FileBackedMap< T >::mMap [private]
The underlying map in memory.
Definition at line 243 of file FileBackedMap.h.
Referenced by FileBackedMap< StopListItem >::begin(), FileBackedMap< StopListItem >::clear(), FileBackedMap< StopListItem >::contains(), FileBackedMap< StopListItem >::count(), FileBackedMap< StopListItem >::empty(), FileBackedMap< StopListItem >::end(), FileBackedMap< StopListItem >::get(), FileBackedMap< StopListItem >::load(), FileBackedMap< StopListItem >::put(), FileBackedMap< StopListItem >::remove(), and FileBackedMap< StopListItem >::save().
The documentation for this class was generated from the following file:
FileBackedMap.h