Garmin Fleet Management Controller: Logger Class Reference
Logger Class Reference
Log writer //!
#include <Logger.h>
Static Public Member Functions
static void clearLog ()
Empties the packet log //!
static void closeLog ()
Close the log file.
static bool isLogOpen ()
Returns true if the log file is open.
static void logRawData (Packet *aPacket, bool aIsTx=true)
Logs the raw data of the packet passed in to a file.
Static Public Attributes
static const char * LOG_FILE = "fmi_pc_app.log"
The log file that this Logger writes to.
Private Member Functions
Logger ()
Construct a new Logger.
virtual ~Logger ()
Destructor.
Static Private Attributes
static std::wofstream mLogFile
File stream that the packet log is written to.
static SYSTEMTIME mLogStartTime
Time when the packet log was started/cleared; used to compute //! offsets.
Detailed Description
Log writer //!
The logger writes the packet log.
Definition at line 24 of file Logger.h.
Constructor & Destructor Documentation
Logger::Logger () [private]
Construct a new Logger.
virtual Logger::~Logger () [private, virtual]
Destructor.
Member Function Documentation
void Logger::clearLog () [static]
Empties the packet log //!
Closes and reopens the log file (removing any existing //! data), writes a start time entry with the current time, and //! sends a notification message that the log has changed.
Definition at line 83 of file Logger.cpp.
References EVENT_LOG_PACKET, LOG_FILE, mLogFile, mLogStartTime, and Event::post().
Referenced by SerialPort::init(), CLogViewerDlg::OnBnClickedClearLog(), and CFmiPcAppDlg::OnFileClearPacketLog().
void Logger::closeLog () [static]
Close the log file.
Definition at line 102 of file Logger.cpp.
References mLogFile.
Referenced by CFmiApplication::~CFmiApplication().
bool Logger::isLogOpen () [static]
Returns true if the log file is open.
Definition at line 111 of file Logger.cpp.
References mLogFile.
Referenced by SerialPort::init().
void Logger::logRawData (Packet * aPacket, bool aIsTx = true) [static]
Logs the raw data of the packet passed in to a file.
Parameters:
aPacket The packet to log //!
aIsTx If true, this packet was transmitted (if false, this //! packet was received)
Definition at line 31 of file Logger.cpp.
References EVENT_LOG_PACKET, Packet::getRawBytes(), Packet::getRawSize(), max_uint_val, mLogStartTime, and Event::post().
Referenced by GarminLinkLayer::getPacketFromFifo(), and GarminLinkLayer::tx().
Member Data Documentation
const char * Logger::LOG_FILE = "fmi_pc_app.log" [static]
The log file that this Logger writes to.
Definition at line 37 of file Logger.h.
Referenced by clearLog(), CLogViewerDlg::OnBnClickedClearLog(), CLogViewerDlg::OnBnClickedViewCurrent(), CLogViewerDlg::OnInitDialog(), and CLogViewerDlg::resetView().
std::wofstream Logger::mLogFile [static, private]
File stream that the packet log is written to.
Definition at line 52 of file Logger.h.
Referenced by clearLog(), closeLog(), and isLogOpen().
SYSTEMTIME Logger::mLogStartTime [static, private]
Time when the packet log was started/cleared; used to compute //! offsets.
Definition at line 49 of file Logger.h.
Referenced by clearLog(), and logRawData().
The documentation for this class was generated from the following files:
Logger.h
Logger.cpp