Garmin Fleet Management Controller: CSelectCommPortDlg Class Reference
CSelectCommPortDlg Class Reference
Modal dialog allowing the user to select the port to use to //! communicate with the client.
#include <CSelectCommPortDlg.h>
Public Member Functions
CSelectCommPortDlg (CWnd *aParent=NULL)
Constructor //!
virtual ~CSelectCommPortDlg ()
Destructor.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *aDataExchange)
Perform dialog data exchange and validation //!
afx_msg void OnBnClickedCancel ()
Click handler for the Cancel button //!
afx_msg void OnBnClickedOk ()
Click handler for the OK button //!
BOOL OnInitDialog ()
Initialize the dialog //!
Protected Attributes
int mSelectedPortIndex
Index of the selected port in the drop down.
Detailed Description
Modal dialog allowing the user to select the port to use to //! communicate with the client.
Definition at line 19 of file CSelectCommPortDlg.h.
Constructor & Destructor Documentation
CSelectCommPortDlg::CSelectCommPortDlg (CWnd * aParent = NULL)
Constructor //!
Parameters:
aParent The parent of this dialog
Definition at line 27 of file CSelectCommPortDlg.cpp.
CSelectCommPortDlg::~CSelectCommPortDlg () [virtual]
Destructor.
Definition at line 38 of file CSelectCommPortDlg.cpp.
Member Function Documentation
void CSelectCommPortDlg::DoDataExchange (CDataExchange * aDataExchange) [protected, virtual]
Perform dialog data exchange and validation //!
Parameters:
aDataExchange The DDX context
Definition at line 47 of file CSelectCommPortDlg.cpp.
References IDC_COMPORT_CBO_PORT.
void CSelectCommPortDlg::OnBnClickedCancel () [protected]
Click handler for the Cancel button //!
Close the dialog.
Definition at line 110 of file CSelectCommPortDlg.cpp.
void CSelectCommPortDlg::OnBnClickedOk () [protected]
Click handler for the OK button //!
Starts the init process with the Com Port chosen.
Definition at line 89 of file CSelectCommPortDlg.cpp.
References SerialPort::getInstance(), SerialPort::getLastError(), IDC_COMPORT_CBO_PORT, mSelectedPortIndex, and TRUE.
BOOL CSelectCommPortDlg::OnInitDialog () [protected]
Initialize the dialog //!
This function is called when the window is created. It //! sets up the parent, so it can get info from and send a message //! to Com. It also enumerates the serial ports on the system //! (trying both the registry and CreateFile methods) and updates //! the combo box with the list of ports found. //!
Returns:
TRUE, since this function does not set focus to a control
Definition at line 65 of file CSelectCommPortDlg.cpp.
References SerialPort::getPortList(), and IDC_COMPORT_CBO_PORT.
Member Data Documentation
int CSelectCommPortDlg::mSelectedPortIndex [protected]
Index of the selected port in the drop down.
Definition at line 45 of file CSelectCommPortDlg.h.
Referenced by OnBnClickedOk().
The documentation for this class was generated from the following files:
CSelectCommPortDlg.h
CSelectCommPortDlg.cpp