Garmin Fleet Management Controller: CGpiTransferDlg Class Reference
CGpiTransferDlg Class Reference
Modal dialog allowing the user to select a GPI file to //! transfer to the client. //!
#include <CGpiTransferDlg.h>
Public Member Functions
CGpiTransferDlg (CWnd *aParent, FmiApplicationLayer &aCom)
Constructor //!
virtual ~CGpiTransferDlg ()
Destructor.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *aDataExchange)
Perform dialog data exchange and validation //!
afx_msg void OnBnClickedFind ()
Click handler for Find (file to send) button. //!
afx_msg void OnBnClickedOk ()
Click handler for OK button. //!
afx_msg void OnEnChangeGpiFile ()
Edit Change handler for all text boxes. //!
BOOL OnInitDialog ()
Initialize the dialog //!
Protected Attributes
FmiApplicationLayer & mCom
Reference to the FMI communication controller.
CString mGpiFilePath
Path and file name of the GPI file to transfer, as specified //! by the user.
CString mVersion
GPI mVersion string specified by the user.
Detailed Description
Modal dialog allowing the user to select a GPI file to //! transfer to the client. //!
Since:
Protocol A604
Definition at line 20 of file CGpiTransferDlg.h.
Constructor & Destructor Documentation
CGpiTransferDlg::CGpiTransferDlg (CWnd * aParent, FmiApplicationLayer & aCom)
Constructor //!
Parameters:
aParent The parent of this dialog //!
aCom Reference to the FMI communication controller
Definition at line 35 of file CGpiTransferDlg.cpp.
CGpiTransferDlg::~CGpiTransferDlg () [virtual]
Destructor.
Definition at line 49 of file CGpiTransferDlg.cpp.
Member Function Documentation
void CGpiTransferDlg::DoDataExchange (CDataExchange * aDataExchange) [protected, virtual]
Perform dialog data exchange and validation //!
Parameters:
aDataExchange The DDX context
Definition at line 58 of file CGpiTransferDlg.cpp.
References IDC_GPIXFER_EDIT_FILE_VERSION, and IDC_GPIXFER_EDIT_FILENAME.
void CGpiTransferDlg::OnBnClickedFind () [protected]
Click handler for Find (file to send) button. //!
Displays a File..Open dialog allowing the user to select the file to send.
Definition at line 122 of file CGpiTransferDlg.cpp.
References FALSE, mGpiFilePath, OnEnChangeGpiFile(), and TRUE.
void CGpiTransferDlg::OnBnClickedOk () [protected]
Click handler for OK button. //!
Initiates the file transfer process. Actual packets are //! sent by the mCom itself, but the file entered is checked before //! sending the message. If the file exists, a GPI File Progress //! dialog box will appear that will not let the user continue until the file transfer completes or the user cancels it. If //! the file doesn't exist, an error dialog will appear.
Definition at line 168 of file CGpiTransferDlg.cpp.
References FmiApplicationLayer::mClientCodepage, mCom, mGpiFilePath, minval, mVersion, FmiApplicationLayer::sendGpiFile(), TRUE, and UTIL_hex_to_uint8().
void CGpiTransferDlg::OnEnChangeGpiFile () [protected]
Edit Change handler for all text boxes. //!
Enables the OK button if both a file name and mVersion are //! specified, and the mVersion is of the appropriate length
Definition at line 85 of file CGpiTransferDlg.cpp.
References FALSE, mGpiFilePath, mVersion, and TRUE.
Referenced by OnBnClickedFind().
BOOL CGpiTransferDlg::OnInitDialog () [protected]
Initialize the dialog //!
This function is called when the window is created. It //! sets up the parent, so it can get info from and send a message //! to FmiApplicationLayer. //!
Returns:
TRUE, since this function does not set focus to a control
Definition at line 74 of file CGpiTransferDlg.cpp.
Member Data Documentation
FmiApplicationLayer& CGpiTransferDlg::mCom [protected]
Reference to the FMI communication controller.
Definition at line 45 of file CGpiTransferDlg.h.
Referenced by OnBnClickedOk().
CString CGpiTransferDlg::mGpiFilePath [protected]
Path and file name of the GPI file to transfer, as specified //! by the user.
Definition at line 49 of file CGpiTransferDlg.h.
Referenced by OnBnClickedFind(), OnBnClickedOk(), and OnEnChangeGpiFile().
CString CGpiTransferDlg::mVersion [protected]
GPI mVersion string specified by the user.
Definition at line 52 of file CGpiTransferDlg.h.
Referenced by OnBnClickedOk(), and OnEnChangeGpiFile().
The documentation for this class was generated from the following files:
CGpiTransferDlg.h
CGpiTransferDlg.cpp