Garmin Fleet Management Controller: CManageCannedResponseDlg Class Reference
CManageCannedResponseDlg Class Reference
Dialog allowing the user to manage canned responses. //!
#include <CManageCannedResponseDlg.h>