Garmin Fleet Management Controller: TimerManager Class Reference
TimerManager Class Reference
Manages timer (periodic) events. //!
#include <TimerManager.h>
Static Public Member Functions
static void addListener (TimerListener *aListener)
Register a listener to receive periodic callbacks
static void removeListener (TimerListener *aListener)
Remove a TimerListener from the list that is called.
static void tick ()
Timer tick //!
Private Member Functions
TimerManager ()
Constructor.
virtual ~TimerManager ()
Destructor.
void instanceAddListener (TimerListener *aListener)
Register a listener to receive periodic callbacks
void instanceRemoveListener (TimerListener *aListener)
Remove a TimerListener from the list that is called.
void instanceTick ()
Timer tick //!
Static Private Member Functions
static void destroyInstance ()
Destroy the TimerManager instance //!
static TimerManager * getInstance ()
Get the TimerManager instance //!
Private Attributes
std::list< TimerListener * > mListeners
List of objects that will get periodic notifications.
Static Private Attributes
static TimerManager * sInstance = NULL
Pointer to the one and only TimerManager instance.
Detailed Description
Manages timer (periodic) events. //!
The TimerManager manages the list of TimerListener objects //! in the application, and periodically calls their onTimer //! function. The application is responsible for periodically //! calling tick().
Definition at line 25 of file TimerManager.h.
Constructor & Destructor Documentation
TimerManager::TimerManager () [private]
Constructor.
Definition at line 45 of file TimerManager.cpp.
TimerManager::~TimerManager () [private, virtual]
Destructor.
Definition at line 52 of file TimerManager.cpp.
Member Function Documentation
void TimerManager::addListener (TimerListener * aListener) [static]
Register a listener to receive periodic callbacks
Parameters:
aListener The listener object to add
Definition at line 61 of file TimerManager.cpp.
Referenced by TimerListener::TimerListener().
void TimerManager::destroyInstance () [static, private]
Destroy the TimerManager instance //!
Destroy the one and only TimerManager.
Definition at line 36 of file TimerManager.cpp.
References sInstance.
Referenced by getInstance().
TimerManager * TimerManager::getInstance () [static, private]
Get the TimerManager instance //!
Get the instance of the TimerManager, constructing it if //! necessary.
Definition at line 22 of file TimerManager.cpp.
References destroyInstance(), and sInstance.
Referenced by tick().
void TimerManager::instanceAddListener (TimerListener * aListener) [private]
Register a listener to receive periodic callbacks
Parameters:
aListener The listener object to add
Definition at line 73 of file TimerManager.cpp.
void TimerManager::instanceRemoveListener (TimerListener * aListener) [private]
Remove a TimerListener from the list that is called.
Parameters:
aListener The listener to remove
Definition at line 98 of file TimerManager.cpp.
void TimerManager::instanceTick () [private]
Timer tick //!
This function is called periodically and distributes the //! timer event to all TimerListnener objects.
Definition at line 121 of file TimerManager.cpp.
References mListeners.
Referenced by tick().
void TimerManager::removeListener (TimerListener * aListener) [static]
Remove a TimerListener from the list that is called.
Parameters:
aListener The aListener to remove
Definition at line 86 of file TimerManager.cpp.
Referenced by TimerListener::~TimerListener().
void TimerManager::tick () [static]
Timer tick //!
This function is called periodically and distributes the //! timer event to all TimerListnener objects.
Definition at line 111 of file TimerManager.cpp.
References getInstance(), and instanceTick().
Referenced by CFmiPcAppDlg::OnTimer().
Member Data Documentation
std::list<TimerListener *> TimerManager::mListeners [private]
List of objects that will get periodic notifications.
Definition at line 61 of file TimerManager.h.
Referenced by instanceTick().
TimerManager * TimerManager::sInstance = NULL [static, private]
Pointer to the one and only TimerManager instance.
Definition at line 58 of file TimerManager.h.
Referenced by destroyInstance(), and getInstance().
The documentation for this class was generated from the following files:
TimerManager.h
TimerManager.cpp