Garmin Fleet Management Controller: CSelectCannedResponseDlg Class Reference
CSelectCannedResponseDlg Class Reference
Dialog allowing the user to select the canned responses //! that are allowed for a particular message. //!
#include <CSelectCannedResponseDlg.h>
Public Member Functions
CSelectCannedResponseDlg (const MessageId &aMessageId, char *aMessageText, uint8 aMessageType, CWnd *aParent, FmiApplicationLayer &aCom)
Constructor //!
virtual ~CSelectCannedResponseDlg ()
Destructor.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *aDataExchange)
Perform dialog data exchange and validation //!
afx_msg void OnBnClickedOk ()
OK button handler //!
BOOL OnInitDialog ()
This function is called when the window is created.
Protected Attributes
FmiApplicationLayer & mCom
Reference to the FMI communication controller.
CListBox mListBox
List box containing the canned responses.
MessageId mMessageId
The message ID passed in from the CNewTxtMsgDlg.
char mMessageText [200]
The message text passed in from the CNewTxtMsgDlg.
uint8 mMessageType
The message type passed in from the CNewTxtMsgDlg //!
Detailed Description
Dialog allowing the user to select the canned responses //! that are allowed for a particular message. //!
Because the protocol cannot be started until the user has // selected the message IDs, all required information to send the text message is passed from the CNewTxtMsgDlg via the / constructor. Then, when the user clicks OK in this dialog, //! all the information is passed to FmiApplicationLayer, which //! sends all of the packets. //!
Note:
The global list of canned responses is created using the //! CManageCannedResponseDlg. //!
Since:
Protocol A604
Definition at line 29 of file CSelectCannedResponseDlg.h.
Constructor & Destructor Documentation
CSelectCannedResponseDlg::CSelectCannedResponseDlg (const MessageId & aMessageId, char * aMessageText, uint8 aMessageType, CWnd * aParent, FmiApplicationLayer & aCom)
Constructor //!
Parameters:
aMessageId The message ID of the message to send //!
aMessageText The message text to send; must be //! null-terminated //!
aMessageType The message_type; see the a604_message_type //! enum //!
aParent Reference to the parent window //!
aCom Reference to the FMI communication controller
Definition at line 34 of file CSelectCannedResponseDlg.cpp.
CSelectCannedResponseDlg::~CSelectCannedResponseDlg () [virtual]
Destructor.
Definition at line 52 of file CSelectCannedResponseDlg.cpp.
Member Function Documentation
void CSelectCannedResponseDlg::DoDataExchange (CDataExchange * aDataExchange) [protected, virtual]
Perform dialog data exchange and validation //!
Parameters:
aDataExchange The DDX context
Definition at line 61 of file CSelectCannedResponseDlg.cpp.
References IDC_RESPSEL_LST_RESPONSES.
void CSelectCannedResponseDlg::OnBnClickedOk () [protected]
OK button handler //!
Extracts data from the form and sends a canned response //! text message via FmiApplicationLayer.
Definition at line 98 of file CSelectCannedResponseDlg.cpp.
References FileBackedMap< T >::getKeyAt(), FmiApplicationLayer::mCannedResponses, mCom, mListBox, mMessageId, mMessageText, mMessageType, FmiApplicationLayer::sendCannedResponseTextMessage(), and TRUE.
BOOL CSelectCannedResponseDlg::OnInitDialog () [protected]
This function is called when the window is created.
Builds the list box of canned responses that the user can //! select from. //!
Returns:
TRUE, since this function does not set focus to a control
Definition at line 75 of file CSelectCannedResponseDlg.cpp.
References FileBackedMap< T >::begin(), FileBackedMap< T >::end(), FmiApplicationLayer::mCannedResponses, mCom, and mListBox.
Member Data Documentation
FmiApplicationLayer& CSelectCannedResponseDlg::mCom [protected]
Reference to the FMI communication controller.
Definition at line 54 of file CSelectCannedResponseDlg.h.
Referenced by OnBnClickedOk(), and OnInitDialog().
CListBox CSelectCannedResponseDlg::mListBox [protected]
List box containing the canned responses.
Definition at line 57 of file CSelectCannedResponseDlg.h.
Referenced by OnBnClickedOk(), and OnInitDialog().
MessageId CSelectCannedResponseDlg::mMessageId [protected]
The message ID passed in from the CNewTxtMsgDlg.
Definition at line 64 of file CSelectCannedResponseDlg.h.
Referenced by OnBnClickedOk().
char CSelectCannedResponseDlg::mMessageText[200] [protected]
The message text passed in from the CNewTxtMsgDlg.
Definition at line 67 of file CSelectCannedResponseDlg.h.
Referenced by OnBnClickedOk().
uint8 CSelectCannedResponseDlg::mMessageType [protected]
The message type passed in from the CNewTxtMsgDlg //!
See also:
a604_message_type for valid values
Definition at line 61 of file CSelectCannedResponseDlg.h.
Referenced by OnBnClickedOk().
The documentation for this class was generated from the following files:
CSelectCannedResponseDlg.h
CSelectCannedResponseDlg.cpp