Garmin Fleet Management Controller: ClientListItem Class Reference
ClientListItem Class Reference
Stores the name associated with a list item //! that is sent to the client. //!
#include <ClientListItem.h>