Garmin Fleet Management Controller: WaypointListItem Class Reference
WaypointListItem Class Reference
Tracks a waypoint that has been sent to the client.
#include <WaypointListItem.h>