Garmin Fleet Management Controller: LogParser Class Reference
LogParser Class Reference
Abstract base class for log item parsers //!
#include <LogParser.h>