//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logictracker.Parametrizacion {
    
    
    public partial class Parametrizacion_EstadoLogDuplicar {
        
        /// <summary>
        /// TitleBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.ToolBar.TitleBar TitleBar1;
        
        /// <summary>
        /// ProgressLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ProgressLabel ProgressLabel1;
        
        /// <summary>
        /// infoLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.InfoLabel infoLabel1;
        
        /// <summary>
        /// lblPlanta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Labels.ResourceLabel lblPlanta;
        
        /// <summary>
        /// upplanta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upplanta;
        
        /// <summary>
        /// lbPlanta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.ListBoxs.PlantaListBox lbPlanta;
        
        /// <summary>
        /// btnDuplicate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Logictracker.Web.CustomWebControls.Buttons.ResourceButton btnDuplicate;
    }
}
