//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class OPERACIONES
{

    private OPERACIONESOPERACION[] oPERACIONField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("OPERACION")]
    public OPERACIONESOPERACION[] OPERACION
    {
        get
        {
            return this.oPERACIONField;
        }
        set
        {
            this.oPERACIONField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OPERACIONESOPERACION
{

    private OPERACIONESOPERACIONDISTRITO dISTRITOField;

    private OPERACIONESOPERACIONBASE bASEField;

    private OPERACIONESOPERACIONVEHICULO vEHICULOField;

    private OPERACIONESOPERACIONDISPOSITIVO dISPOSITIVOField;

    private uOperacion movimientoField;

    private string transField;

    /// <comentarios/>
    public OPERACIONESOPERACIONDISTRITO DISTRITO
    {
        get
        {
            return this.dISTRITOField;
        }
        set
        {
            this.dISTRITOField = value;
        }
    }

    /// <comentarios/>
    public OPERACIONESOPERACIONBASE BASE
    {
        get
        {
            return this.bASEField;
        }
        set
        {
            this.bASEField = value;
        }
    }

    /// <comentarios/>
    public OPERACIONESOPERACIONVEHICULO VEHICULO
    {
        get
        {
            return this.vEHICULOField;
        }
        set
        {
            this.vEHICULOField = value;
        }
    }

    /// <comentarios/>
    public OPERACIONESOPERACIONDISPOSITIVO DISPOSITIVO
    {
        get
        {
            return this.dISPOSITIVOField;
        }
        set
        {
            this.dISPOSITIVOField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uOperacion movimiento
    {
        get
        {
            return this.movimientoField;
        }
        set
        {
            this.movimientoField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string trans
    {
        get
        {
            return this.transField;
        }
        set
        {
            this.transField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OPERACIONESOPERACIONDISTRITO
{

    private string razsocField;

    private string codigoField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string razsoc
    {
        get
        {
            return this.razsocField;
        }
        set
        {
            this.razsocField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codigo
    {
        get
        {
            return this.codigoField;
        }
        set
        {
            this.codigoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OPERACIONESOPERACIONBASE
{

    private string codigoField;

    private string descripcionField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codigo
    {
        get
        {
            return this.codigoField;
        }
        set
        {
            this.codigoField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descripcion
    {
        get
        {
            return this.descripcionField;
        }
        set
        {
            this.descripcionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OPERACIONESOPERACIONVEHICULO
{

    private string tipovField;

    private string dominioField;

    private string internoField;

    private string marcaField;

    private string modeloField;

    private uVEstado estadoField;

    private bool visibleField;

    public OPERACIONESOPERACIONVEHICULO()
    {
        this.estadoField = uVEstado.O;
        this.visibleField = true;
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipov
    {
        get
        {
            return this.tipovField;
        }
        set
        {
            this.tipovField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dominio
    {
        get
        {
            return this.dominioField;
        }
        set
        {
            this.dominioField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string interno
    {
        get
        {
            return this.internoField;
        }
        set
        {
            this.internoField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marca
    {
        get
        {
            return this.marcaField;
        }
        set
        {
            this.marcaField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modelo
    {
        get
        {
            return this.modeloField;
        }
        set
        {
            this.modeloField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(uVEstado.O)]
    public uVEstado estado
    {
        get
        {
            return this.estadoField;
        }
        set
        {
            this.estadoField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool visible
    {
        get
        {
            return this.visibleField;
        }
        set
        {
            this.visibleField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum uVEstado
{

    /// <comentarios/>
    O,

    /// <comentarios/>
    I,

    /// <comentarios/>
    M,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OPERACIONESOPERACIONDISPOSITIVO
{

    private string tipoField;

    private string identField;

    private string imeiField;

    private string lineaField;

    private uVEstado estadoField;

    public OPERACIONESOPERACIONDISPOSITIVO()
    {
        this.estadoField = uVEstado.O;
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipo
    {
        get
        {
            return this.tipoField;
        }
        set
        {
            this.tipoField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ident
    {
        get
        {
            return this.identField;
        }
        set
        {
            this.identField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imei
    {
        get
        {
            return this.imeiField;
        }
        set
        {
            this.imeiField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string linea
    {
        get
        {
            return this.lineaField;
        }
        set
        {
            this.lineaField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(uVEstado.O)]
    public uVEstado estado
    {
        get
        {
            return this.estadoField;
        }
        set
        {
            this.estadoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum uOperacion
{

    /// <comentarios/>
    A,

    /// <comentarios/>
    B,

    /// <comentarios/>
    M,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Respuesta
{

    private RespuestaSessionId sessionIdField;

    private RespuestaActive activeField;

    private RespuestaLogout logoutField;

    private RespuestaImport[] importField;

    private RespuestaError[] errorField;

    /// <comentarios/>
    public RespuestaSessionId SessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }

    /// <comentarios/>
    public RespuestaActive Active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <comentarios/>
    public RespuestaLogout Logout
    {
        get
        {
            return this.logoutField;
        }
        set
        {
            this.logoutField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Import")]
    public RespuestaImport[] Import
    {
        get
        {
            return this.importField;
        }
        set
        {
            this.importField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Error")]
    public RespuestaError[] Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RespuestaSessionId
{

    private string valueField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RespuestaActive
{

    private bool valueField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public bool Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RespuestaLogout
{

    private bool valueField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public bool Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RespuestaImport
{

    private string transField;

    private string valueField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string trans
    {
        get
        {
            return this.transField;
        }
        set
        {
            this.transField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RespuestaError
{

    private string transField;

    private string valueField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string trans
    {
        get
        {
            return this.transField;
        }
        set
        {
            this.transField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Error
{

    private ErrorMensaje mensajeField;

    /// <comentarios/>
    public ErrorMensaje Mensaje
    {
        get
        {
            return this.mensajeField;
        }
        set
        {
            this.mensajeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ErrorMensaje
{

    private string valueField;

    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
