//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logictracker.Scheduler.Tasks.LoJack.LoJackApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoJackApi.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoEntidades", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesResponse GetInfoEntidades(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoEntidad", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadResponse GetInfoEntidad(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecorrido", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoResponse GetRecorrido(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUltimosSucesos", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosResponse GetUltimosSucesos(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetNombreEntidad", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadResponse SetNombreEntidad(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltaAreaCircular", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularResponse AltaAreaCircular(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoEntidadArea", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaResponse GetInfoEntidadArea(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdEntidadFromDominio", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioResponse GetIdEntidadFromDominio(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaControlFromId", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdResponse GetAreaControlFromId(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarEventosTemperatura", ReplyAction="*")]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaResponse ConsultarEventosTemperatura(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEntidadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEntidades", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequestBody Body;
        
        public GetInfoEntidadesRequest() {
        }
        
        public GetInfoEntidadesRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoEntidadesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        public GetInfoEntidadesRequestBody() {
        }
        
        public GetInfoEntidadesRequestBody(string userLogin, string userPassword, string GUID) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEntidadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEntidadesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesResponseBody Body;
        
        public GetInfoEntidadesResponse() {
        }
        
        public GetInfoEntidadesResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoEntidadesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidades GetInfoEntidadesResult;
        
        public GetInfoEntidadesResponseBody() {
        }
        
        public GetInfoEntidadesResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidades GetInfoEntidadesResult) {
            this.GetInfoEntidadesResult = GetInfoEntidadesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEntidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEntidad", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequestBody Body;
        
        public GetInfoEntidadRequest() {
        }
        
        public GetInfoEntidadRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoEntidadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dominio;
        
        public GetInfoEntidadRequestBody() {
        }
        
        public GetInfoEntidadRequestBody(string userLogin, string userPassword, string GUID, string dominio) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.dominio = dominio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEntidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEntidadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadResponseBody Body;
        
        public GetInfoEntidadResponse() {
        }
        
        public GetInfoEntidadResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoEntidadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidad GetInfoEntidadResult;
        
        public GetInfoEntidadResponseBody() {
        }
        
        public GetInfoEntidadResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidad GetInfoEntidadResult) {
            this.GetInfoEntidadResult = GetInfoEntidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecorridoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecorrido", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequestBody Body;
        
        public GetRecorridoRequest() {
        }
        
        public GetRecorridoRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecorridoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime fechaHasta;
        
        public GetRecorridoRequestBody() {
        }
        
        public GetRecorridoRequestBody(string userLogin, string userPassword, string GUID, string dominio, System.DateTime fechaDesde, System.DateTime fechaHasta) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.dominio = dominio;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecorridoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecorridoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoResponseBody Body;
        
        public GetRecorridoResponse() {
        }
        
        public GetRecorridoResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecorridoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoRecorrido GetRecorridoResult;
        
        public GetRecorridoResponseBody() {
        }
        
        public GetRecorridoResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoRecorrido GetRecorridoResult) {
            this.GetRecorridoResult = GetRecorridoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUltimosSucesosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUltimosSucesos", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequestBody Body;
        
        public GetUltimosSucesosRequest() {
        }
        
        public GetUltimosSucesosRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUltimosSucesosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idSucesoRegistro;
        
        public GetUltimosSucesosRequestBody() {
        }
        
        public GetUltimosSucesosRequestBody(string userLogin, string userPassword, string GUID, int idSucesoRegistro) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.idSucesoRegistro = idSucesoRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUltimosSucesosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUltimosSucesosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosResponseBody Body;
        
        public GetUltimosSucesosResponse() {
        }
        
        public GetUltimosSucesosResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUltimosSucesosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoUltimosSucesos GetUltimosSucesosResult;
        
        public GetUltimosSucesosResponseBody() {
        }
        
        public GetUltimosSucesosResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoUltimosSucesos GetUltimosSucesosResult) {
            this.GetUltimosSucesosResult = GetUltimosSucesosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetNombreEntidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetNombreEntidad", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequestBody Body;
        
        public SetNombreEntidadRequest() {
        }
        
        public SetNombreEntidadRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetNombreEntidadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nombreEntidad;
        
        public SetNombreEntidadRequestBody() {
        }
        
        public SetNombreEntidadRequestBody(string userLogin, string userPassword, string GUID, string dominio, string nombreEntidad) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.dominio = dominio;
            this.nombreEntidad = nombreEntidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetNombreEntidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetNombreEntidadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadResponseBody Body;
        
        public SetNombreEntidadResponse() {
        }
        
        public SetNombreEntidadResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetNombreEntidadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.Resultado SetNombreEntidadResult;
        
        public SetNombreEntidadResponseBody() {
        }
        
        public SetNombreEntidadResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.Resultado SetNombreEntidadResult) {
            this.SetNombreEntidadResult = SetNombreEntidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaAreaCircularRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaAreaCircular", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequestBody Body;
        
        public AltaAreaCircularRequest() {
        }
        
        public AltaAreaCircularRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaAreaCircularRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.AreaItem[] areas;
        
        public AltaAreaCircularRequestBody() {
        }
        
        public AltaAreaCircularRequestBody(string userLogin, string userPassword, string GUID, Logictracker.Interfaces.LoJackApi.LoJackApi.AreaItem[] areas) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.areas = areas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaAreaCircularResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaAreaCircularResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularResponseBody Body;
        
        public AltaAreaCircularResponse() {
        }
        
        public AltaAreaCircularResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaAreaCircularResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInsertAreas AltaAreaCircularResult;
        
        public AltaAreaCircularResponseBody() {
        }
        
        public AltaAreaCircularResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInsertAreas AltaAreaCircularResult) {
            this.AltaAreaCircularResult = AltaAreaCircularResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEntidadAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEntidadArea", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequestBody Body;
        
        public GetInfoEntidadAreaRequest() {
        }
        
        public GetInfoEntidadAreaRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoEntidadAreaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idEntidad;
        
        public GetInfoEntidadAreaRequestBody() {
        }
        
        public GetInfoEntidadAreaRequestBody(string userLogin, string userPassword, string GUID, int idEntidad) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.idEntidad = idEntidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEntidadAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEntidadAreaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaResponseBody Body;
        
        public GetInfoEntidadAreaResponse() {
        }
        
        public GetInfoEntidadAreaResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoEntidadAreaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidadArea GetInfoEntidadAreaResult;
        
        public GetInfoEntidadAreaResponseBody() {
        }
        
        public GetInfoEntidadAreaResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidadArea GetInfoEntidadAreaResult) {
            this.GetInfoEntidadAreaResult = GetInfoEntidadAreaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdEntidadFromDominioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdEntidadFromDominio", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequestBody Body;
        
        public GetIdEntidadFromDominioRequest() {
        }
        
        public GetIdEntidadFromDominioRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIdEntidadFromDominioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dominio;
        
        public GetIdEntidadFromDominioRequestBody() {
        }
        
        public GetIdEntidadFromDominioRequestBody(string userLogin, string userPassword, string GUID, string dominio) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.dominio = dominio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdEntidadFromDominioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdEntidadFromDominioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioResponseBody Body;
        
        public GetIdEntidadFromDominioResponse() {
        }
        
        public GetIdEntidadFromDominioResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIdEntidadFromDominioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoEntidad GetIdEntidadFromDominioResult;
        
        public GetIdEntidadFromDominioResponseBody() {
        }
        
        public GetIdEntidadFromDominioResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoEntidad GetIdEntidadFromDominioResult) {
            this.GetIdEntidadFromDominioResult = GetIdEntidadFromDominioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaControlFromIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaControlFromId", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequestBody Body;
        
        public GetAreaControlFromIdRequest() {
        }
        
        public GetAreaControlFromIdRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaControlFromIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idAreaControl;
        
        public GetAreaControlFromIdRequestBody() {
        }
        
        public GetAreaControlFromIdRequestBody(string userLogin, string userPassword, string GUID, int idAreaControl) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.idAreaControl = idAreaControl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaControlFromIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaControlFromIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdResponseBody Body;
        
        public GetAreaControlFromIdResponse() {
        }
        
        public GetAreaControlFromIdResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaControlFromIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoArea GetAreaControlFromIdResult;
        
        public GetAreaControlFromIdResponseBody() {
        }
        
        public GetAreaControlFromIdResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoArea GetAreaControlFromIdResult) {
            this.GetAreaControlFromIdResult = GetAreaControlFromIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEventosTemperaturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEventosTemperatura", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequestBody Body;
        
        public ConsultarEventosTemperaturaRequest() {
        }
        
        public ConsultarEventosTemperaturaRequest(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarEventosTemperaturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ArrayOfString dominios;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime fechaHasta;
        
        public ConsultarEventosTemperaturaRequestBody() {
        }
        
        public ConsultarEventosTemperaturaRequestBody(string userLogin, string userPassword, string GUID, Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ArrayOfString dominios, System.DateTime fechaDesde, System.DateTime fechaHasta) {
            this.userLogin = userLogin;
            this.userPassword = userPassword;
            this.GUID = GUID;
            this.dominios = dominios;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEventosTemperaturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEventosTemperaturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaResponseBody Body;
        
        public ConsultarEventosTemperaturaResponse() {
        }
        
        public ConsultarEventosTemperaturaResponse(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarEventosTemperaturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoEventosTemperatura ConsultarEventosTemperaturaResult;
        
        public ConsultarEventosTemperaturaResponseBody() {
        }
        
        public ConsultarEventosTemperaturaResponseBody(Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoEventosTemperatura ConsultarEventosTemperaturaResult) {
            this.ConsultarEventosTemperaturaResult = ConsultarEventosTemperaturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap>, Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetInfoEntidades(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequest request) {
            return base.Channel.GetInfoEntidades(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidades GetInfoEntidades(string userLogin, string userPassword, string GUID) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadesResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetInfoEntidades(inValue);
            return retVal.Body.GetInfoEntidadesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetInfoEntidad(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequest request) {
            return base.Channel.GetInfoEntidad(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidad GetInfoEntidad(string userLogin, string userPassword, string GUID, string dominio) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.dominio = dominio;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetInfoEntidad(inValue);
            return retVal.Body.GetInfoEntidadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetRecorrido(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequest request) {
            return base.Channel.GetRecorrido(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoRecorrido GetRecorrido(string userLogin, string userPassword, string GUID, string dominio, System.DateTime fechaDesde, System.DateTime fechaHasta) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.dominio = dominio;
            inValue.Body.fechaDesde = fechaDesde;
            inValue.Body.fechaHasta = fechaHasta;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetRecorridoResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetRecorrido(inValue);
            return retVal.Body.GetRecorridoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetUltimosSucesos(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequest request) {
            return base.Channel.GetUltimosSucesos(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoUltimosSucesos GetUltimosSucesos(string userLogin, string userPassword, string GUID, int idSucesoRegistro) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.idSucesoRegistro = idSucesoRegistro;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetUltimosSucesosResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetUltimosSucesos(inValue);
            return retVal.Body.GetUltimosSucesosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.SetNombreEntidad(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequest request) {
            return base.Channel.SetNombreEntidad(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.Resultado SetNombreEntidad(string userLogin, string userPassword, string GUID, string dominio, string nombreEntidad) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.dominio = dominio;
            inValue.Body.nombreEntidad = nombreEntidad;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.SetNombreEntidadResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).SetNombreEntidad(inValue);
            return retVal.Body.SetNombreEntidadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.AltaAreaCircular(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequest request) {
            return base.Channel.AltaAreaCircular(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInsertAreas AltaAreaCircular(string userLogin, string userPassword, string GUID, Logictracker.Interfaces.LoJackApi.LoJackApi.AreaItem[] areas) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.areas = areas;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.AltaAreaCircularResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).AltaAreaCircular(inValue);
            return retVal.Body.AltaAreaCircularResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetInfoEntidadArea(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequest request) {
            return base.Channel.GetInfoEntidadArea(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoInfoEntidadArea GetInfoEntidadArea(string userLogin, string userPassword, string GUID, int idEntidad) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.idEntidad = idEntidad;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetInfoEntidadAreaResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetInfoEntidadArea(inValue);
            return retVal.Body.GetInfoEntidadAreaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetIdEntidadFromDominio(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequest request) {
            return base.Channel.GetIdEntidadFromDominio(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoEntidad GetIdEntidadFromDominio(string userLogin, string userPassword, string GUID, string dominio) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.dominio = dominio;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetIdEntidadFromDominioResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetIdEntidadFromDominio(inValue);
            return retVal.Body.GetIdEntidadFromDominioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.GetAreaControlFromId(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequest request) {
            return base.Channel.GetAreaControlFromId(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoArea GetAreaControlFromId(string userLogin, string userPassword, string GUID, int idAreaControl) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.idAreaControl = idAreaControl;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.GetAreaControlFromIdResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).GetAreaControlFromId(inValue);
            return retVal.Body.GetAreaControlFromIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaResponse Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap.ConsultarEventosTemperatura(Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequest request) {
            return base.Channel.ConsultarEventosTemperatura(request);
        }
        
        public Logictracker.Interfaces.LoJackApi.LoJackApi.ResultadoEventosTemperatura ConsultarEventosTemperatura(string userLogin, string userPassword, string GUID, Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ArrayOfString dominios, System.DateTime fechaDesde, System.DateTime fechaHasta) {
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequest inValue = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequest();
            inValue.Body = new Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.userPassword = userPassword;
            inValue.Body.GUID = GUID;
            inValue.Body.dominios = dominios;
            inValue.Body.fechaDesde = fechaDesde;
            inValue.Body.fechaHasta = fechaHasta;
            Logictracker.Scheduler.Tasks.LoJack.LoJackApi.ConsultarEventosTemperaturaResponse retVal = ((Logictracker.Scheduler.Tasks.LoJack.LoJackApi.Service1Soap)(this)).ConsultarEventosTemperatura(inValue);
            return retVal.Body.ConsultarEventosTemperaturaResult;
        }
    }
}
