#region Usings

using System.Reflection;
using System.Runtime.InteropServices;
using System.Web.UI;

#endregion

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("CustomWebControls")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("b")]
[assembly: AssemblyProduct("CustomWebControls")]
[assembly: AssemblyCopyright("Copyright © b 2008")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a T in this assembly from 
// COM, set the ComVisible attribute to true on that T.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("457ecb8c-aeca-4d05-bbce-dcb0831a30eb")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.add.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.copy.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.delete.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.disk.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.map.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.printer.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.list.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.spliter.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.csv.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.excel.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.import.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.regenerate.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.schedule.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.sendReport.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.anular.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.event.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.ToolBar.edit.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Ajax.WebKitHack.js", "text/javascript")]

[assembly: WebResource("Logictracker.Web.CustomWebControls.ListBoxs.ImageListBox.js", "text/javascript")]

[assembly: WebResource("Logictracker.Web.CustomWebControls.Input.DateTimePicker.js", "text/javascript")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Input.calendar.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Input.DateTimeRangeValidator.js", "text/javascript")]

[assembly: WebResource("Logictracker.Web.CustomWebControls.Labels.Popup.baloontip.js", "text/javascript")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Labels.Popup.baloontip.css", "text/css")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Labels.Popup.help.png", "image/png")]

[assembly: WebResource("Logictracker.Web.CustomWebControls.Buttons.connected.png", "image/png")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Buttons.disconnected.png", "image/png")]

[assembly: WebResource("Logictracker.Web.CustomWebControls.Buttons.version.txt", "text/plain")]


// Flag images for Culture Selector
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ad.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ae.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.af.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ag.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ai.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.al.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.am.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.an.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ao.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ar.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.as.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.at.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.au.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.aw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ax.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.az.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ba.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bb.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bd.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.be.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bh.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bi.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bj.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bo.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.br.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bs.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bv.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.by.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.bz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ca.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.catalonia.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cd.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ch.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ci.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ck.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cl.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.co.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cs.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cv.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cx.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cy.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.cz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.de.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.dj.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.dk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.dm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.do.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.dz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ec.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ee.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.eg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.eh.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.england.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.er.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.es.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.et.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.europeanunion.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fam.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fi.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fj.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.flags.txt", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fo.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.fr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ga.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gb.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gd.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ge.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gh.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gi.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gl.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gp.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gq.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gs.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.gy.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.hk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.hm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.hn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.hr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ht.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.hu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.id.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ie.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.il.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.in.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.io.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.iq.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ir.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.is.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.it.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.jm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.jo.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.jp.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ke.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kh.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ki.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.km.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kp.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ky.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.kz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.la.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lb.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.li.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ls.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.lv.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ly.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ma.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.md.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.me.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mh.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ml.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mo.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mp.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mq.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ms.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mv.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mx.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.my.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.mz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.na.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.nc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ne.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.nf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ng.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ni.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.nl.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.no.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.np.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.nr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.nu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.nz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.om.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pa.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pe.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ph.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pl.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ps.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.pw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.py.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.qa.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.re.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ro.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.rs.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ru.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.rw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sa.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sb.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.scotland.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sd.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.se.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sh.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.si.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sj.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sl.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.so.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.st.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sv.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sy.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.sz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.td.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.th.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tj.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tk.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tl.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.to.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tr.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tv.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tw.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.tz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ua.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ug.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.um.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.us.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.uy.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.uz.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.va.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.vc.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ve.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.vg.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.vi.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.vn.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.vu.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.wales.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.wf.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ws.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.ye.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.yt.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.za.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.zm.gif", "image/gif")]
[assembly: WebResource("Logictracker.Web.CustomWebControls.Culture.flags.zw.gif", "image/gif")]